<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<OutputPath>..\wwwroot\housebrokerapp</OutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<OutputPath>..\wwwroot\housebrokerapp</OutputPath>
	</PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Properties\launchSettings.json" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Properties\launchSettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.5" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>
	
	
  <ItemGroup>
    <ProjectReference Include="..\HouseBrokerApp.Application\HouseBrokerApp.Application.csproj" />
    <ProjectReference Include="..\HouseBrokerApp.Infrastructure\HouseBrokerApp.Infrastructure.csproj" />
  </ItemGroup>

</Project>
