<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<OutputPath>..\wwwroot\housebrokerapp</OutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<OutputPath>..\wwwroot\housebrokerapp</OutputPath>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\HouseBrokerApp.Domain\HouseBrokerApp.Domain.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

</Project>
